name: Notify Telegram on Merge to Main/Master

on:
  push:
    branches:
      - main
      - master
      # Add a Persistent Volume Claim (PVC) for storage


jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot8101075525:AAF-_x06By1BN7yyB6oH7b7bu9egu1SYgSY/sendMessage" \
            -d chat_id=1069089370 \
            -d text="🚨 Merge to Main/Master Branch 🚨\nA merge has been made to the main/master branch. Please review the changes!"